from django.urls import path
from . import views
from .views import InspectionCreateView, InspectionListView, InspectionUpdateView, delete_inspection,CompletedInspectionListView,add_quotation, service_list, service_create, service_edit, service_delete,manage_insurances,manage_roadtax
from .views import (
    InspectionCreateView,
    InspectionListView,
    CompletedInspectionListView,
    InspectionUpdateView,
    delete_inspection,
    inspection_details
)
from .views import check_driver_code,   driver_login_jwt,driver_profile

urlpatterns=[
    path('',views.login,name='login'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path("dashboard-counts/", views.dashboard_counts, name="dashboard_counts"),
    path("alerts/services/",views.service_alert_data,name="service_alerts"),
    path("alerts/fuel/", views.fuel_alerts, name="fuel_alerts"),
    path( "alerts/inspections/",views.inspection_alerts,name="inspection_alerts"),
    path('manageparts/',views.manageparts,name='manageparts'),
    path('add',views.add,name='add'),
    path('edit',views.edit,name='edit'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('create/',views.create,name='create'),
    path('createadd',views.createadd,name='createadd'),
    path('createedit/<int:id>',views.createedit,name='createedit'),
    path('createupdate/<int:id>',views.createupdate,name='createupdate'),
    path('createdelete/<int:id>',views.createdelete,name='createdelete'),
    path('inspection/',views.inspection,name='inspection'),
    path('inspectadd',views.inspectadd,name='inspectadd'),
    path('inspectedit',views.inspectedit,name='inspectedit'),
    path('inspectupdate/<int:id>',views.inspectupdate,name='inspectupdate'),
    path('inspectdelete/<int:id>',views.inspectdelete,name='inspectdelete'),
    path('expense/',views.expense,name='expense'),
    path('expenseadd',views.expenseadd,name='expenseadd'),
    path('expenseedit',views.expenseedit,name='expenseedit'),
    path('expenseupdate/<int:id>',views.expenseupdate,name='expenseupdate'),
    path('expensedelete/<int:id>',views.expensedelete,name='expensedelete'),
    path('fueltype/',views.fueltype,name='fueltype'),
    path('fueltypeadd',views.fueltypeadd,name='fueltypeadd'),
    path('fueltypeedit',views.fueltypeedit,name='fueltypeedit'),
    path('fueltypeupdate/<int:id>',views.fueltypeupdate,name='fueltypeupdate'),
    path('fueltypedelete/<int:id>',views.fueltypedelete,name='fueltypedelete'),
    path('service/',views.service,name='service'),
    path('serviceadd',views.serviceadd,name='serviceadd'),
    path('serviceedit',views.serviceedit,name='serviceedit'),
    path('serviceupdate/<int:id>',views.serviceupdate,name='serviceupdate'),
    path('servicedelete/<int:id>',views.servicedelete,name='servicedelete'),
    path('inspectionreq/',views.inspectionreq,name='inspectionreq'),
    path('InspectionListView', InspectionListView.as_view(), name='inspection_list'),
    path('inspection_update/<int:pk>', InspectionUpdateView.as_view(), name='inspection_update'),
    path('inspectioncreate/', InspectionCreateView.as_view(), name='inspection_create'),  # ✅ KEEP THIS
    path('<int:pk>/delete/', delete_inspection, name='inspection_delete'),
    #path('inspectioncreate/', views.create_inspection_request, name='create_inspection_request'),
    path('inspection/complete/', CompletedInspectionListView.as_view(), name='completed_inspection_list'),
    path('inspection/<int:pk>/details/', inspection_details, name='inspection_details'),
    path("quotations/", views.quotation_list, name="quatlist"),
    path("quotations/add/", views.add_quotation, name="newquat"),
    path("quotations/<int:id>/edit/", views.edit_quotation, name="edit_quat"),
    path("quotations/<int:id>/delete/", views.delete_quotation, name="delete_quat"),
    path("quotations/approved/", views.approved_quotations, name="approved_quotations"),
    path('vehicles/', views.manage_vehicles, name='manage_vehicles'),
    path('vehicles/add/', views.add_vehicle, name='add_vehicle'),
    path('vehicles/edit/<int:vehicle_id>/', views.edit_vehicle, name='edit_vehicle'),
    path('vehicles/delete/<int:vehicle_id>/', views.delete_vehicle, name='delete_vehicle'),
    path('vehicles/<int:vehicle_id>/', views.vehicle_details, name='vehicle_details'),
    path('drivers/', views.manage_drivers, name='manage_drivers'),
    path('drivers/add/', views.add_driver, name='add_driver'),
    path('drivers/edit/<int:driver_id>/', views.edit_driver, name='edit_driver'),
    path('drivers/delete/<int:driver_id>/', views.delete_driver, name='delete_driver'),
    path('driver-reviews/', views.driver_reviews, name='driver_reviews'),
    path('driver-reviews/add/', views.add_review, name='add_review'),
    path('driver-reviews/edit/<int:review_id>/', views.edit_review, name='edit_review'),
    path('driver-reviews/delete/<int:review_id>/', views.delete_review, name='delete_review'),
    path('manage-other-expenses/', views.manage_other_expenses, name='manage_other_expenses'),
    path('add-other-expense/', views.add_other_expense, name='add_other_expense'),
    path('edit-other-expense/<int:pk>/', views.edit_other_expense, name='edit_other_expense'),
    path('delete-other-expense/<int:pk>/', views.delete_other_expense, name='delete_other_expense'),
    path("fueling/add/", views.add_or_update_fueling, name="add_fueling"),
    path("fueling/edit/<int:pk>/", views.add_or_update_fueling, name="edit_fueling"),
    path("fueling/report/", views.fuel_report_list, name="fuel_report_list"),
    path("fueling/delete/<int:pk>/", views.delete_fueling, name="delete_fueling"),
    path('tyre/manage/', views.manage_tyre, name='manage_tyre'),
    path('tyre/add/', views.add_tyre, name='add_tyre'),
    path('tyre/edit/<int:pk>/', views.edit_tyre, name='edit_tyre'),
    path('tyre/delete/<int:pk>/', views.delete_tyre, name='delete_tyre'),
    path('manageitems/', views.ManageItemsView.as_view(), name='manageitems'),
    path('additem/', views.AddItemView.as_view(), name='add_item'),
    path('edititem/<int:pk>/', views.EditItemView.as_view(), name='edit_item'),
    path('deleteitem/<int:pk>/', views.DeleteItemView.as_view(), name='delete_item'),
    path('services/', views.service_list, name='service_list'),
    path('services/new/', views.service_create, name='service_create'),
    # path('services/<int:pk>/', views.service_detail, name='service_detail'),
    path('services/<int:pk>/edit/', views.service_edit, name='service_edit'),
    path('services/<int:pk>/delete/', views.service_delete, name='service_delete'),
    path('vendors/', views.vendor_list, name='vendor_list'),
    path('vendors/add/', views.vendor_add_update, name='vendor_add'),
    path('vendors/edit/<int:vendor_id>/', views.vendor_add_update, name='vendor_edit'),
    path('vendor/delete/<int:vendor_id>/', views.vendor_delete, name='vendor_delete'),
    path('purchases/', views.purchase_list, name='purchase_list'),
    path('purchases/new/', views.create_purchase, name='create_purchase'),
    path('purchases/<int:pk>/edit/', views.edit_purchase, name='edit_purchase'),
    path('purchases/<int:pk>/delete/', views.delete_purchase, name='delete_purchase'),
    path('services/typewise/', views.typewise, name='typewise'),
    path('insurances/', views.manage_insurances, name='manage_insurances'),
    path('manage-registrations/', views.manage_registrations, name='manage_registrations'),
    path('manage-roadtax/', views.manage_roadtax, name='manage_roadtax'),
    path('manage-puc/', views.manage_puc, name='manage_puc'),
    path('manage-permit/', views.manage_permit, name='manage_permit'),
    path('manage-fitness/', views.manage_fitness, name='manage_fitness'),
    path('mileage/', views.mileage, name='mileage'),
    path('api/check-driver/', check_driver_code),
    path('api/jwt-login/', driver_login_jwt),
    path('api/driver-profile/', driver_profile),
    path("api/update-location/", views.update_location),

]