# Generated by Django 5.2.4 on 2025-08-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('CreatedBy', models.CharField(max_length=50)),
                ('CreatedDate', models.CharField(max_length=100)),
                ('UpdatedBy', models.CharField(max_length=50)),
                ('UpdatedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
