# Generated by Django 5.2.4 on 2025-08-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0002_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='Category',
            new_name='BrandModels',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='CreatedBy',
            new_name='Created',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='UpdatedDate',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='CreatedDate',
            new_name='Location',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='UpdatedBy',
        ),
        migrations.AddField(
            model_name='owner',
            name='OwnerName',
            field=models.CharField(default='Unknown Owner', max_length=100),
            preserve_default=False,
        ),
    ]
