# Generated by Django 5.2.4 on 2025-08-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0004_inspects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspects',
            old_name='Category',
            new_name='INCategory',
        ),
        migrations.RenameField(
            model_name='inspects',
            old_name='CreatedBy',
            new_name='INCreatedBy',
        ),
        migrations.RenameField(
            model_name='inspects',
            old_name='CreatedDate',
            new_name='INCreatedDate',
        ),
        migrations.RenameField(
            model_name='inspects',
            old_name='UpdatedBy',
            new_name='INUpdatedBy',
        ),
        migrations.RenameField(
            model_name='inspects',
            old_name='UpdatedDate',
            new_name='INUpdatedDate',
        ),
    ]
