# Generated by Django 5.2.4 on 2025-08-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0005_rename_category_inspects_incategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EXCategory', models.CharField(max_length=100)),
                ('EXCreatedBy', models.CharField(max_length=50)),
                ('EXCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('EXUpdatedBy', models.CharField(max_length=50)),
                ('EXUpdatedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
