# Generated by Django 5.2.4 on 2025-08-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0006_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='EXUpdatedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inspects',
            name='INUpdatedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='manage',
            name='UpdatedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='owner',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
