# Generated by Django 5.2.4 on 2025-08-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0007_alter_expenses_exupdateddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspects',
            name='INUpdatedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manage',
            name='UpdatedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
