# Generated by Django 5.2.4 on 2025-08-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0008_alter_inspects_inupdateddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='EXUpdatedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
