# Generated by Django 5.2.4 on 2025-08-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0009_alter_expenses_exupdateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='EXUpdatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
