# Generated by Django 5.2.4 on 2025-08-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0010_alter_expenses_exupdateddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fueltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FUCategory', models.CharField(max_length=100)),
                ('FUCreatedBy', models.CharField(max_length=50)),
                ('FUCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('FUUpdatedBy', models.CharField(max_length=50)),
                ('FUUpdatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
