# Generated by Django 5.2.4 on 2025-08-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0011_fueltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERCategory', models.CharField(max_length=100)),
                ('SERCreatedBy', models.CharField(max_length=50)),
                ('SERCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('SERUpdatedBy', models.CharField(max_length=50)),
                ('SERUpdatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
