# Generated by Django 5.2.4 on 2025-08-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0012_servicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATSNO', models.IntegerField(max_length=50)),
                ('STATDate', models.DateTimeField(auto_now=True)),
                ('STATInspectionCode', models.CharField(max_length=50)),
                ('STATVehicle', models.CharField(max_length=50)),
                ('STATAssignedManager', models.CharField(max_length=50)),
                ('STATManagerNo', models.IntegerField(max_length=50)),
                ('STATInseptionType', models.CharField(max_length=50)),
                ('STATStatus', models.CharField(max_length=50)),
                ('STATCreatedBy', models.CharField(max_length=50)),
            ],
        ),
    ]
