# Generated by Django 5.2.4 on 2025-08-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0013_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='STATPlateNo',
            field=models.CharField(default='unkown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='STATTitle',
            field=models.CharField(default='Unkown Plateno', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspection',
            name='STATManagerNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='STATSNO',
            field=models.IntegerField(),
        ),
    ]
