# Generated by Django 5.2.4 on 2025-08-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0014_inspection_statplateno_inspection_stattitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('manager', models.CharField(choices=[('Select Manager', 'Select Manager'), ('John Smith', 'John Smith'), ('Aisha Khan', 'Aisha Khan'), ('Carlos Ramirez', 'Carlos Ramirez'), ('Emily Zhang', 'Emily Zhang'), ('David Osei', 'David Osei')], max_length=100)),
                ('inspection_type', models.CharField(choices=[('Pre-Purchase Inspection', 'Pre-Purchase Inspection'), ('Annual Inspection', 'Annual Inspection')], max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Reinspection Required', 'Reinspection Required')], default='Completed', max_length=50)),
                ('vehicle', models.CharField(choices=[('Car 1', 'Car 1'), ('Car 2', 'Car 2')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='inspection',
            old_name='STATDate',
            new_name='STATCreatedDate',
        ),
        migrations.RenameField(
            model_name='inspection',
            old_name='STATAssignedManager',
            new_name='STATInseptiontitle',
        ),
        migrations.RenameField(
            model_name='inspection',
            old_name='STATCreatedBy',
            new_name='STATManager',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='STATManagerNo',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='STATPlateNo',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='STATSNO',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='STATTitle',
        ),
        migrations.AlterField(
            model_name='inspection',
            name='STATInspectionCode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='STATVehicle',
            field=models.CharField(max_length=20),
        ),
    ]
