# Generated by Django 5.2.4 on 2025-08-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0015_inspectionrequest_inspectiontype_vehicle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='STATInseptionType',
            new_name='STATInseptiontype',
        ),
    ]
