# Generated by Django 5.2.4 on 2025-08-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0016_rename_statinseptiontype_inspection_statinseptiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrequest',
            name='inspection_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
