# Generated by Django 5.2.4 on 2025-08-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0017_inspectionrequest_inspection_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrequest',
            name='inspection_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
