# Generated by Django 5.2.4 on 2025-08-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0018_alter_inspectionrequest_inspection_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrequest',
            name='inspection_code',
            field=models.CharField(blank=True, default='INSP-0001', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
