# Generated by Django 5.2.4 on 2025-08-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0019_alter_inspectionrequest_inspection_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrequest',
            name='inspection_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
