# Generated by Django 5.2.4 on 2025-08-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0020_alter_inspectionrequest_inspection_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionrequest',
            name='inspection_code',
        ),
    ]
