# Generated by Django 5.2.4 on 2025-08-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0021_remove_inspectionrequest_inspection_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='EXUpdatedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='FUUpdatedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inspects',
            name='INUpdatedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manage',
            name='UpdatedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='SERUpdatedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
