# Generated by Django 5.2.4 on 2025-08-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0022_alter_expenses_exupdatedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrequest',
            name='inspection_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
