# Generated by Django 5.2.4 on 2025-09-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0023_inspectionrequest_inspection_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrequest',
            name='inspection_type',
            field=models.CharField(choices=[('Pre-Purchase Inspection', 'Pre-Purchase Inspection'), ('Annual Inspection', 'Annual Inspection'), ('Fleet Inspection', 'Fleet Inspection'), ('Accident Inspection', 'Accident Inspection'), ('Tire Inspection', 'Tire Inspection'), ('Brake Inspection', 'Brake Inspection'), ('Vehicle Exterior Inspection', 'Vehicle Exterior Inspection')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='vehicle',
            field=models.CharField(choices=[('Xylo', 'Xylo'), ('Scorpio', 'Scorpio'), ('Bolero', 'Bolero')], max_length=100),
        ),
    ]
