# Generated by Django 5.2.4 on 2025-09-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0024_alter_inspectionrequest_inspection_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=50, unique=True)),
                ('quotation_date', models.DateField()),
                ('vehicle_name', models.CharField(max_length=100)),
                ('plate_no', models.CharField(max_length=20)),
                ('inspection_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateField()),
            ],
        ),
    ]
