# Generated by Django 5.2.4 on 2025-09-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0025_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='plate_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_no',
            field=models.CharField(max_length=50),
        ),
    ]
