# Generated by Django 5.2.4 on 2025-09-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0026_alter_quotation_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='plate_no',
            field=models.CharField(choices=[('Engine and Mechanical', 'Engine and Mechanical'), ('Electrical and Lighting', 'Electrical and Lighting'), ('Suspension and steering', 'Suspension and steering'), ('Braking System', 'Braking System')], max_length=100),
        ),
    ]
