# Generated by Django 5.2.4 on 2025-09-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0027_alter_quotation_plate_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
