# Generated by Django 5.2.4 on 2025-09-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0028_alter_quotation_quotation_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='inspection_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
