# Generated by Django 5.2.4 on 2025-09-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0030_remove_vehicle_plate_number_vehicle_chassis_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('plate_no', models.CharField(max_length=20, unique=True)),
                ('fuel_type', models.CharField(max_length=20)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('make_year', models.IntegerField(blank=True, null=True)),
                ('manufacture_year', models.IntegerField(blank=True, null=True)),
                ('engine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('chassis_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ownership', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model_adv', models.CharField(blank=True, max_length=100, null=True)),
                ('tyre_size', models.CharField(blank=True, max_length=50, null=True)),
                ('tons', models.CharField(blank=True, max_length=50, null=True)),
                ('odometer', models.IntegerField(blank=True, null=True)),
                ('insurance_no', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_start', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('roadtax_last', models.DateField(blank=True, null=True)),
                ('permit_last', models.DateField(blank=True, null=True)),
                ('puc_last', models.DateField(blank=True, null=True)),
                ('reg_from', models.DateField(blank=True, null=True)),
                ('reg_to', models.DateField(blank=True, null=True)),
                ('fitness_end', models.DateField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
