# Generated by Django 5.2.4 on 2025-09-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0031_newvehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewVehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='chassis_no',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='engine_no',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='make',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='make_year',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='plate_no',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
