# Generated by Django 5.2.4 on 2025-09-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0033_vehicle_chassis_no_vehicle_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fitness_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fitness Certificate End'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(blank=True, choices=[('Canada', 'Canada'), ('USA', 'USA')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_adv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ownership',
            field=models.CharField(blank=True, choices=[('Greenline Logistics', 'Greenline Logistics'), ('Company Fleet', 'Company Fleet')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='permit_last',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='puc_last',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='reg_from',
            field=models.DateField(blank=True, null=True, verbose_name='Registration From'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='reg_to',
            field=models.DateField(blank=True, null=True, verbose_name='Registration To'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='roadtax_last',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tons',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tyre_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
