# Generated by Django 5.2.4 on 2025-09-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0034_vehicle_brand_vehicle_fitness_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
    ]
