# Generated by Django 5.2.4 on 2025-10-05 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0035_vehicle_image1_vehicle_image2_vehicle_image3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_full_name', models.CharField(max_length=100)),
                ('driver_contact_number', models.CharField(max_length=15)),
                ('driver_email_address', models.EmailField(blank=True, max_length=100, null=True)),
                ('driver_home_address', models.TextField(blank=True, null=True)),
                ('driver_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('driver_license_number', models.CharField(max_length=50, unique=True)),
                ('driver_license_expiry', models.DateField(blank=True, null=True)),
                ('driver_character_cert_expiry', models.DateField(blank=True, null=True)),
                ('driver_explosive_cert_expiry', models.DateField(blank=True, null=True)),
                ('driver_training_cert_expiry', models.DateField(blank=True, null=True)),
                ('driver_emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('driver_created_by', models.CharField(default='system', max_length=50)),
                ('driver_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver_updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_updated_on', models.DateTimeField(auto_now=True)),
                ('driver_profile_image', models.ImageField(blank=True, null=True, upload_to='driver_profiles/')),
            ],
        ),
    ]
