# Generated by Django 5.2.4 on 2025-10-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0036_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_license_number',
            field=models.CharField(max_length=50),
        ),
    ]
