# Generated by Django 5.2.4 on 2025-10-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0037_alter_driver_driver_license_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_mobile', models.CharField(max_length=15)),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=3)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_by', models.CharField(max_length=100)),
                ('driver_image', models.URLField(blank=True, help_text="Optional URL to the driver's image", max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Driver Review',
                'verbose_name_plural': 'Driver Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
