# Generated by Django 5.2.4 on 2025-10-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0038_driverreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverreview',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
