# Generated by Django 5.2.4 on 2025-10-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0039_alter_driverreview_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverreview',
            old_name='created_by',
            new_name='recreated_by',
        ),
    ]
