# Generated by Django 5.2.4 on 2025-10-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0040_rename_created_by_driverreview_recreated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverreview',
            name='driver_image',
        ),
    ]
