# Generated by Django 5.2.4 on 2025-10-06 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0041_remove_driverreview_driver_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_reference_no', models.CharField(max_length=50, unique=True)),
                ('exp_date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('exp_vehicle_label', models.CharField(max_length=100)),
                ('exp_vehicle_tag', models.CharField(max_length=50)),
                ('exp_category_label', models.CharField(max_length=100)),
                ('exp_description_title', models.CharField(max_length=200)),
                ('exp_total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exp_odometer_reading', models.PositiveIntegerField(blank=True, null=True)),
                ('exp_bill_number', models.CharField(max_length=100, unique=True)),
                ('exp_bill_attachment', models.FileField(blank=True, null=True, upload_to='expense_docs/')),
                ('exp_driver_ref', models.CharField(max_length=100)),
                ('exp_created_person', models.CharField(max_length=100)),
                ('exp_created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('exp_modified_person', models.CharField(blank=True, max_length=100, null=True)),
                ('exp_modified_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
