# Generated by Django 5.2.4 on 2025-10-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0042_otherexpenserecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherexpenserecord',
            name='exp_reference_no',
            field=models.CharField(max_length=50),
        ),
    ]
