# Generated by Django 5.2.4 on 2025-10-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0043_alter_otherexpenserecord_exp_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherexpenserecord',
            name='exp_bill_number',
            field=models.CharField(max_length=100),
        ),
    ]
