# Generated by Django 5.2.4 on 2025-10-08 12:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0044_alter_otherexpenserecord_exp_bill_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fueling_date', models.DateField(default=django.utils.timezone.now)),
                ('fuel_station', models.CharField(max_length=150)),
                ('fuel_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online'), ('Credit', 'Credit')], default='Cash', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleetapp.driver')),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleetapp.fueltype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetapp.vehicle')),
            ],
        ),
    ]
