# Generated by Django 5.2.4 on 2025-10-08 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0045_fuelreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelreport',
            old_name='updated_by',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='fuelreport',
            old_name='created_date',
            new_name='created_datetime',
        ),
        migrations.RenameField(
            model_name='fuelreport',
            old_name='fuel_cost',
            new_name='fuel_price_per_liter',
        ),
        migrations.RenameField(
            model_name='fuelreport',
            old_name='fuel_quantity',
            new_name='fuel_quantity_liters',
        ),
        migrations.RenameField(
            model_name='fuelreport',
            old_name='remarks',
            new_name='fuel_remarks',
        ),
        migrations.RenameField(
            model_name='fuelreport',
            old_name='total_amount',
            new_name='fuel_total_amount',
        ),
        migrations.RenameField(
            model_name='fuelreport',
            old_name='updated_date',
            new_name='updated_datetime',
        ),
        migrations.RemoveField(
            model_name='fuelreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fuelreport',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='fuelreport',
            name='fuel_station',
        ),
        migrations.RemoveField(
            model_name='fuelreport',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='fuelreport',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='fuel_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_reports', to='fleetapp.driver'),
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='fuel_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='fuel_odometer_reading',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='fuel_station_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='fuel_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleetapp.vehicle'),
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='updated_by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuelreport',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_reports', to='fleetapp.fueltype'),
        ),
    ]
