# Generated by Django 5.2.4 on 2025-10-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0046_rename_updated_by_fuelreport_created_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelreport',
            name='fuel_price_per_liter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuelreport',
            name='fuel_quantity_liters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuelreport',
            name='fuel_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuelreport',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG')], default='Petrol', max_length=10),
        ),
    ]
