# Generated by Django 5.2.4 on 2025-10-10 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0047_alter_fuelreport_fuel_price_per_liter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherexpenserecord',
            name='exp_created_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherexpenserecord',
            name='exp_date_recorded',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
