# Generated by Django 5.2.4 on 2025-10-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0048_alter_otherexpenserecord_exp_created_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherexpenserecord',
            name='exp_vehicle_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
