# Generated by Django 5.2.4 on 2025-10-10 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0050_alter_otherexpenserecord_exp_date_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherexpenserecord',
            name='exp_date_recorded',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
