# Generated by Django 5.2.4 on 2025-10-10 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0051_alter_otherexpenserecord_exp_date_recorded'),
    ]

    operations = [
        migrations.CreateModel(
            name='TyreReplacementRecord',
            fields=[
                ('tyre_replacement_id', models.AutoField(primary_key=True, serialize=False)),
                ('tyre_replacement_date', models.DateField(default=django.utils.timezone.now, verbose_name='Tyre Replacement Date')),
                ('tyre_vehicle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Name')),
                ('tyre_brand_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand Name')),
                ('tyre_size_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tyre Size')),
                ('tyre_unique_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tyre Number')),
                ('tyre_type_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tyre Type')),
                ('tyre_replace_reason_text', models.TextField(blank=True, null=True, verbose_name='Replace Reason')),
                ('tyre_odometer_reading_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer Reading')),
                ('tyre_driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Driver Name')),
                ('tyre_description_details', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('tyre_bill_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bill Number')),
                ('tyre_bill_document_file', models.FileField(blank=True, null=True, upload_to='tyre_bills/', verbose_name='Bill Document')),
                ('tyre_created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('tyre_updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tyre Replacement Record',
                'verbose_name_plural': 'Tyre Replacement Records',
                'ordering': ['-tyre_replacement_date'],
            },
        ),
    ]
