# Generated by Django 5.2.4 on 2025-10-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0052_tyrereplacementrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PARTCAT_Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PART_PartNo', models.CharField(max_length=50, unique=True)),
                ('PART_Name', models.CharField(max_length=150)),
                ('PART_Description', models.TextField(blank=True, null=True)),
                ('PART_Unit', models.CharField(choices=[('Piece', 'Piece'), ('Set', 'Set'), ('Pack', 'Pack')], max_length=50)),
                ('PART_Remark', models.TextField(blank=True, null=True)),
                ('PART_Price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('PART_Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('PART_Image1', models.ImageField(blank=True, null=True, upload_to='part_images/')),
                ('PART_Image2', models.ImageField(blank=True, null=True, upload_to='part_images/')),
                ('PART_CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('PART_UpdatedAt', models.DateTimeField(auto_now=True)),
                ('PART_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PART_Items', to='fleetapp.partcategory')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-PART_CreatedAt'],
            },
        ),
    ]
