# Generated by Django 5.2.4 on 2025-10-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0053_partcategory_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartCategory',
            new_name='ItemCategory',
        ),
    ]
