# Generated by Django 5.2.4 on 2025-10-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0054_rename_partcategory_itemcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='PART_Category',
            field=models.CharField(choices=[('Engine', 'Engine'), ('Brake', 'Brake'), ('Electrical', 'Electrical')], max_length=50),
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='PART_CreatedAt',
            new_name='CreatedDate',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='PART_UpdatedAt',
            new_name='UpdatedDate',
        ),
        migrations.AddField(
            model_name='item',
            name='PART_Color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='PART_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='PART_Unit',
            field=models.CharField(choices=[('Piece', 'Piece'), ('Box', 'Box'), ('Kg', 'Kg')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
