# Generated by Django 5.2.4 on 2025-10-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0055_alter_item_part_category_alter_item_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(blank=True, max_length=100, null=True)),
                ('service_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('routine', 'Routine Maintenance'), ('engine', 'Engine Repair'), ('oil_change', 'Oil Change'), ('brake', 'Brake Service'), ('transmission', 'Transmission Repair'), ('electrical', 'Electrical System'), ('tyre', 'Tyre Replacement'), ('ac', 'AC/Heating Service'), ('other', 'Other')], max_length=30)),
                ('last_kilometer', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle', models.CharField(choices=[('TN01', 'TN 01 AB 1234 - Toyota Innova'), ('TN02', 'TN 02 CD 5678 - Mahindra Bolero'), ('TN03', 'TN 03 EF 9101 - Maruti Swift'), ('TN04', 'TN 04 GH 1122 - Tata Nexon'), ('TN05', 'TN 05 JK 3344 - Hyundai Creta')], max_length=50)),
                ('service_title', models.CharField(max_length=100)),
                ('next_service_kilometer', models.PositiveIntegerField(blank=True, null=True)),
                ('service_date', models.DateField()),
                ('requested_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('scheduled', 'Scheduled')], max_length=20)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('service_center_name', models.CharField(blank=True, max_length=100, null=True)),
                ('service_assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('labor_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_items_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_third_party_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
