# Generated by Django 5.2.4 on 2025-10-13 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0056_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_part_category', models.CharField(choices=[('engine', 'Engine'), ('brake', 'Brake'), ('electrical', 'Electrical'), ('tyre', 'Tyre'), ('fluid', 'Fluid'), ('filter', 'Filter'), ('battery', 'Battery'), ('other', 'Other')], max_length=50, unique=True)),
                ('entry_part_name', models.CharField(choices=[('engine_oil', 'Engine Oil'), ('brake_pad', 'Brake Pad'), ('air_filter', 'Air Filter'), ('fuel_filter', 'Fuel Filter'), ('spark_plug', 'Spark Plug'), ('car_battery', 'Car Battery'), ('ac_filter', 'AC Filter'), ('coolant', 'Coolant'), ('transmission_fluid', 'Transmission Fluid'), ('tyre', 'Tyre'), ('headlight_bulb', 'Headlight Bulb'), ('wiper_blade', 'Wiper Blade'), ('fan_belt', 'Fan Belt'), ('radiator', 'Radiator'), ('alternator', 'Alternator')], max_length=100, unique=True)),
                ('entry_unit', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('entry_quantity', models.PositiveIntegerField(default=1, unique=True)),
                ('entry_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, unique=True)),
                ('entry_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, unique=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fleetapp.service')),
            ],
        ),
    ]
