# Generated by Django 5.2.4 on 2025-10-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0057_serviceentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceentry',
            name='entry_part_category',
            field=models.CharField(choices=[('engine', 'Engine'), ('brake', 'Brake'), ('electrical', 'Electrical'), ('tyre', 'Tyre'), ('fluid', 'Fluid'), ('filter', 'Filter'), ('battery', 'Battery'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='entry_part_name',
            field=models.CharField(choices=[('engine_oil', 'Engine Oil'), ('brake_pad', 'Brake Pad'), ('air_filter', 'Air Filter'), ('fuel_filter', 'Fuel Filter'), ('spark_plug', 'Spark Plug'), ('car_battery', 'Car Battery'), ('ac_filter', 'AC Filter'), ('coolant', 'Coolant'), ('transmission_fluid', 'Transmission Fluid'), ('tyre', 'Tyre'), ('headlight_bulb', 'Headlight Bulb'), ('wiper_blade', 'Wiper Blade'), ('fan_belt', 'Fan Belt'), ('radiator', 'Radiator'), ('alternator', 'Alternator')], max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='entry_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='entry_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='entry_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='entry_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
