# Generated by Django 5.2.4 on 2025-10-14 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0058_alter_serviceentry_entry_part_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
