# Generated by Django 5.2.4 on 2025-10-17 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0059_service_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorName', models.CharField(max_length=100)),
                ('vendorCompanyName', models.CharField(blank=True, max_length=150, null=True)),
                ('vendorGender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('vendorEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('vendorMobileNo', models.CharField(blank=True, max_length=15, null=True)),
                ('vendorLandlineNo', models.CharField(blank=True, max_length=15, null=True)),
                ('vendorAddress', models.TextField(blank=True, null=True)),
                ('vendorCountry', models.CharField(blank=True, max_length=100, null=True)),
                ('vendorState', models.CharField(blank=True, max_length=100, null=True)),
                ('vendorCity', models.CharField(blank=True, max_length=100, null=True)),
                ('vendorRemark', models.TextField(blank=True, null=True)),
                ('vendorProfileImage', models.ImageField(blank=True, null=True, upload_to='vendors/')),
                ('vendorCreatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('vendorCreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendorUpdatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('vendorUpdatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
