# Generated by Django 5.2.4 on 2025-10-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0060_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendorEmail',
            field=models.CharField(blank=True, null=True),
        ),
    ]
