# Generated by Django 5.2.4 on 2025-10-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0061_alter_vendor_vendoremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendorCreatedBy',
            field=models.CharField(blank=True, default='admin', max_length=100, null=True),
        ),
    ]
