# Generated by Django 5.2.4 on 2025-10-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0062_alter_vendor_vendorcreatedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_title', models.CharField(max_length=150)),
                ('purchase_manager', models.CharField(choices=[('John Smith', 'John Smith'), ('Mary Johnson', 'Mary Johnson'), ('David Wilson', 'David Wilson'), ('Priya Nair', 'Priya Nair'), ('Arun Sharma', 'Arun Sharma')], max_length=100)),
                ('item_type', models.CharField(choices=[('Engine Part', 'Engine Part'), ('Electrical Component', 'Electrical Component'), ('Body Material', 'Body Material'), ('Lubricant', 'Lubricant'), ('Tyre/Brake', 'Tyre/Brake')], max_length=100)),
                ('purchase_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('vendor', models.CharField(choices=[('Bosch Ltd.', 'Bosch Ltd.'), ('Mahindra Spares', 'Mahindra Spares'), ('TVS Auto Parts', 'TVS Auto Parts'), ('Tata Genuine Parts', 'Tata Genuine Parts'), ('Hero MotoCorp Supplies', 'Hero MotoCorp Supplies'), ('SKF Bearings India', 'SKF Bearings India'), ('Castrol Lubricants', 'Castrol Lubricants')], max_length=150)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
