# Generated by Django 5.2.4 on 2025-10-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0063_purchaseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelreport',
            name='fuel_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
