# Generated by Django 5.2.4 on 2026-03-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0064_alter_fuelreport_fuel_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
