# Generated by Django 5.2.4 on 2026-03-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0065_driver_driver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
