# Generated by Django 5.2.4 on 2026-03-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0068_driverlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='status',
            field=models.CharField(choices=[('ON_DUTY', 'On Duty'), ('OFF_DUTY', 'Off Duty')], default='OFF_DUTY', max_length=20),
        ),
    ]
